// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime override for Hydex local model offload.
 *
 * This is intentionally not a persisted TOML setting. `None` at the call site
 * means "use `model_offload.enabled` from config".
 */
export type ModelOffloadRuntimeOverride = "force_on" | "force_off";
