// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime override for Hydex compaction routing.
 *
 * This is intentionally not a persisted TOML setting. `None` at the call site
 * means "use `model_offload.compaction.policy` from config".
 */
export type ModelOffloadCompactionRuntimeOverride = "local" | "primary";
